[tools]
node = "latest"
# bun = "latest"
# python = "latest"
# go = "latest"
# rust = "latest"
"npm:@antfu/ni" = "latest"
"npm:taze" = "latest"

[tasks.upgrade]
description = "Upgrade tools"
run = """
brew upgrade
mise upgrade
"""

[tasks.clean]
description = "Cleanup cache"
run = """
npm cache clean --force
pnpm store prune
corepack cache clean
brew cleanup
"""
